name: app.js Service

on:
  push:
    branches:
      - develop

defaults:
  run:
    working-directory: ./

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: node:12

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: node app.js
        # env:
        #   # use mongodb for the host here because we have specified a container for the job.
        #   # If we were running the job on the VM this would be localhost
        #   MONGODB_HOST: mongodb
        #   MONGODB_PORT: ${{ job.services.mongodb.ports[27017] }}
